name: Wake Up Streamlit

on:
  schedule:
    # Runs at minute 0 past every hour (Every 60 mins)
    - cron: '0 * * * *'
  workflow_dispatch: # Allows you to run it manually to test

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Poke App
        run: |
          curl -I "https://q360insights.streamlit.app/"
