name: Wake Up Streamlit

on:
  schedule:
    # The syntax '*/15' means "Run every 15 minutes"
    - cron: '*/15 * * * *'
  workflow_dispatch: 

jobs:
  wake_app:
    runs-on: ubuntu-latest
    steps:
      - name: Poke App
        run: |
          # The -I flag fetches the header only (lighter request)
          # The -L flag follows redirects (important for Streamlit)
          curl -I -L "https://q360insights.streamlit.app/"
